import type { NextPage } from 'next'
import Head from 'next/head'
import { Container, Grid } from '@mantine/core'
import Sidebar from '../components/Sidebar'
import Content from '../components/Content';

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Container fluid px={0}>
        <div className="flex">
          <Sidebar />
          <Content />
        </div>
      </Container>

    </div>
  )
}

export default Home
