import type { NextPage } from 'next'
import Head from 'next/head'
import { Container } from '@mantine/core'
import Sidebar from '../components/Sidebar'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Container size={1366}>
        <Sidebar />
      </Container>

    </div>
  )
}

export default Home
